alter table COMPANYCHECK_BRANCH add constraint FK_COMPANYCHECK_BRANCH_ON_COMPANY foreign key (COMPANY_ID) references COMPANYCHECK_COMPANY(ID);
create index IDX_COMPANYCHECK_BRANCH_ON_COMPANY on COMPANYCHECK_BRANCH (COMPANY_ID);
