alter table COMPANYCHECK_GENERAL_MANAGER alter column COMPANY_ID rename to COMPANY_ID__U15035 ^
alter table COMPANYCHECK_GENERAL_MANAGER drop constraint FK_COMPANYCHECK_GENERAL_MANAGER_ON_COMPANY ;
drop index IDX_COMPANYCHECK_GENERAL_MANAGER_ON_COMPANY ;
alter table COMPANYCHECK_GENERAL_MANAGER add column MANAGEDCOMPANY_ID varchar(36) ;
